version: '3.9'

services:
  postgres:
    image: postgres:15-alpine # Imagen oficial de PostgreSQL
    container_name: postgres_container
    ports:
      - "5432:5432" # Puerto local:Puerto del contenedor
    environment:
      POSTGRES_USER: user     # Usuario por defecto
      POSTGRES_PASSWORD: pass # Contraseña por defecto
      POSTGRES_DB: mydb       # Base de datos inicial
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistencia de datos

volumes:
  postgres_data:
    driver: local